### ISSUE TITLE
Remove legacy-version-string-field-format section

### ISSUE THREAD

**Issue by daidoji** [trustoverip/tswg-keri-specification#120]
Although entirely appropriate that keripy and associated tools be forced to implement this legacy version string format, for the purpose of this self-contained specification perhaps we ought to remove this section or make it an OPTIONAL or SHOULD for implementers.  

If we want to keep it a SHALL, then maybe its better to just spell it out as we have done so noting particularly that sniffing the message at the VVV vs VV parts of the string are appropriate to differentiate the types of message. 

Or perhaps, as this spec doesn't necessarily depend on any legacy specifications (although production deployments absolutely do) we should remove it as a requirement entirely anticipating these deployments migrate to the protocol as will be specified.

https://trustoverip.github.io/tswg-keri-specification/#legacy-version-string-field-format

**Comment by daidoji** [comment]
As an addendum to this issue, all of the JSON examples in the spec use the legacy version id in their messages and not the one defined as preferred in the spec.  Even if we don't remove the legacy section it may be a good idea to update the versions for all the messages.

**Comment by m00sey** [comment]
Legacy format has been moved to the CESR spec
