### ISSUE TITLE
Add descriptions to all data structures in Section 7.

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/tswg-keri-specification#125]
Currently, many examples of KERI data structures—such as key event messages, receipt messages, etc.—do not have any description. 

It is also unclear what is the meaning of the digest `d` of each message—whether it is a SAID of the message itself or a reference to the SAID of another message. This is specified for the receipts but not for other message types.

**Comment by m00sey** [comment]
@nkongsuwan please re-review we feel this has been normalized

**Comment by nkongsuwan** [comment]
@m00sey 
I have just read the update. So it seems the receipt message is the only exception where `d` refers to a key event and not the message's enclosing block.

I suggest that we add a brief description to describe the purpose of each message type, perhaps one sentence each. Currently, only the fields inside each message and their orders are described. 

For example, I have no idea for what purpose and in which context the `prod message` and `bare message` are used.

**Comment by nkongsuwan** [comment]
I just realized there is a new table describing the messages. https://trustoverip.github.io/tswg-keri-specification/#message-type-field
