### ISSUE TITLE
Fix imagine rendering

### ISSUE THREAD

**Issue by m00sey** [trustoverip/tswg-keri-specification#136]

**Comment by henkvancann** [comment]
See example https://weboftrust.github.io/kerific-spec/ in the title (will only be there temporarily) 
![Screenshot by Dropbox Capture](https://github.com/trustoverip/tswg-keri-specification/assets/479356/2fe49ea4-5d59-4150-bc98-41986c629a64)
and the source See example https://weboftrust.github.io/kerific-spec/ in the title (will only be there temporarily) 

![Screenshot by Dropbox Capture](https://github.com/trustoverip/tswg-keri-specification/assets/479356/9e687861-3d7d-4ce5-8d5d-ad20ffdb00df)

So, the only way to do it is: right click and copy -> in the markdown a full URL.
![Screenshot by Dropbox Capture](https://github.com/trustoverip/tswg-keri-specification/assets/479356/c1a385e2-af61-4339-b6c8-e22c18a2154f)

**Comment by henkvancann** [comment]
By the way, I haven't seen any references in the sources of the ToIP KERI spec, to the images that Sam has prepared in the images subdir of that repo. Right?

**Comment by henkvancann** [comment]
https://github.com/trustoverip/tswg-keri-specification/pull/141
