### ISSUE TITLE
Clarify the meaning of `prod` and `bare` messages.

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/tswg-keri-specification#170]
In [Message type field](https://trustoverip.github.io/tswg-keri-specification/#message-type-field) `Bare` and `Prod` messages are defined in a table but are not clearly explained. Currently, it is still not clear what their purposes are.

I looked into KERIpy a bit and found out their definitions in [eventing.py](https://github.com/WebOfTrust/keripy/blob/development/src/keri/core/eventing.py#L1258)
- [prod](https://github.com/WebOfTrust/keripy/blob/development/src/keri/core/eventing.py#L1258): `msg to request disclosure via bare, 'bar' msg of data anchored via seal(s) on KEL`
- [bare](https://github.com/WebOfTrust/keripy/blob/development/src/keri/core/eventing.py#L1303): `unhiding (bareing) messages for disclosure of sealed data associated with anchored seals in a KEL`

It is still not clear to me what `prod` stands for and why it is called the way it is. Given the definition in KERIpy, the name `prod` doesn't make much sense to me.

**Comment by nkongsuwan** [comment]
It seems `prod` and `bare` are elaborated in [KAPI](https://github.com/WebOfTrust/kapi/blob/main/kapi.md)

**Comment by pfeairheller** [comment]
Sam completed week of 04/29/2024
