### ISSUE TITLE
Transposed fields in 7.3 Delegated Rotation Event Message Body

### ISSUE THREAD

**Issue by dlandi** [trustoverip/tswg-keri-specification#175]
In 7.3, first paragraph your state the required order of the Message properties:
The top-level fields of a Delegated Rotation, drt event message body shall appear in the following order: [ v, t, d, i, s, p, kt, k, nt, n, bt, br, ba, c, a]

![image](https://github.com/trustoverip/tswg-keri-specification/assets/3196088/f7c3f204-c5a3-4b98-8695-68f6c2558dea)

But in the example, the order is bt, ba, br:

![image](https://github.com/trustoverip/tswg-keri-specification/assets/3196088/502cbcc4-7be1-4236-bd4c-1c7810309c53)

The order in either the specification or the example is wrong.

**Comment by SmithSamuelM** [comment]
fixed
