### ISSUE TITLE
KERI foundational overview

### ISSUE THREAD

**Issue by m00sey** [trustoverip/tswg-keri-specification#30]
We need to merge/align these paragraphs under the KERI foundational overview

[This section should be an overview of what would result from the use of all of the following concepts.
Starting with an inception event establishing the initial key state and the first entry on the KEL. 
Witnesses and Watchers put in place.
This forms the basis for an ecosystem and infrastructure based on KERI to support the issuance, verification and revocation of ACDC credentials, leveraging CESR as the encoding protocol.
Plans for rotation events, planned and those in response to potential duplicitous activity]

> This section needs to be added as section 4.1 KERI ecosystem and infrastructure overview of the revised format.  Section 4.2 will follow in the revised format entitled Introduction to CESR encoding

**Comment by SmithSamuelM** [comment]
Include decriptions of components in the watcher network, namely Juror  Pools and Judges of Juror pool
